### ISSUE TITLE
JSONObject being serialized as a string

### ISSUE THREAD

**Issue by ocls** [PayMaya/PayMaya-Android-SDK-v2#11]
Copying email here for record keeping

> Hi all,
> 
> I took some time to look into this problem and I've narrowed it down to the class PayMaya-Android-SDK-v2/sdk/src/main/java/com/paymaya/sdk/android/common/serialization/JSONObjectSerializer.kt. It's currently using strings as the intermediary object for serializing to JSON, which is causing the output to encode it as a string, rather than a JSON object. This can be fixed by converting the JSONObject into the Kotlin serialization library's own JsonObject class instead:
> 
> ```
> import kotlinx.serialization.KSerializer
> import kotlinx.serialization.descriptors.SerialDescriptor
> import kotlinx.serialization.encoding.Decoder
> import kotlinx.serialization.encoding.Encoder
> import kotlinx.serialization.json.Json
> import kotlinx.serialization.json.JsonElement
> import org.json.JSONObject
> 
> class JSONObjectSerializer : KSerializer<JSONObject> {
>     private val serializer = JsonElement.serializer()
>     override val descriptor: SerialDescriptor = serializer.descriptor
> 
>     override fun serialize(encoder: Encoder, value: JSONObject) {
>         val string = value.toString()
>         val temp = Json.parseToJsonElement(string)
>         encoder.encodeSerializableValue(serializer, temp)
>     }
> 
>     override fun deserialize(decoder: Decoder): JSONObject {
>         val temp = decoder.decodeSerializableValue(serializer)
>         val string = temp.toString()
>         return JSONObject(string)
>     }
> }
> ```
> 
> This was coded in Kotlin version 1.4.10, and serialization-core version 1.0.0-RC so the exact implementation will be slightly different for your project.
> 
> Cheers!

**Comment by rjarce** [comment]
Thanks @ocls for reporting. I have replicated the issue and can confirm that this is indeed a bug in the serialization for the metadata fields w/in the SDK. We'll have this checked further.
