### ISSUE TITLE
Move to mavenCentral()?

### ISSUE THREAD

**Issue by yelsane** [PayMaya/PayMaya-Android-SDK-v2#16]
Are there any plans on when the package will be available on maven repo? There's an [artifact on maven](https://search.maven.org/search?q=g:com.paymaya), but it seems to be v1.

JCenter will be kept as a read-only repo _indefinitely_. It'd be great if a reliable version is up just in case they totally get rid of it.

**Comment by rjarce** [comment]
Hi,

We are currently using Jitpack to host our artifacts. For build configuration on your apps, you can refer to this part of the doc: https://github.com/PayMaya/PayMaya-Android-SDK-v2#jitpack.
