### ISSUE TITLE
No Internet Connection (both SDK Demo & other projects that uses)

### ISSUE THREAD

**Issue by jcchikikomori** [PayMaya/PayMaya-Android-SDK-v2#3]
I found this interesting.

The message was still shown even though I have an internet connection (tried both Mobile Data & WiFi)

Here's the image

![image](https://user-images.githubusercontent.com/4709030/81643966-5ce91200-9459-11ea-80de-e27db659aadd.png)

**Comment by rjarce** [comment]
Hi @jcchikikomori , I can't replicate this using my environment. Does this always occur in your environment, for both 4G and wifi? Also, what device/OS are you running on when this issue occurred?

**Comment by jcchikikomori** [comment]
> Hi @jcchikikomori , I can't replicate this using my environment. Does this always occur in your environment, for both 4G and wifi? Also, what device/OS are you running on when this issue occurred?

I understand and i cannot replicate this one for now. But i would suggest to update the UX about this, because there is no message or notic on how to go back or try again (except automatic disable the message)

**Comment by rjarce** [comment]
Thanks @jcchikikomori , will close this ticket for the meantime. Feel free to raise a separate issue so we can discuss the UX improvements you are mentioning about.
