### ISSUE TITLE
Android Lollipop support

### ISSUE THREAD

**Issue by jcchikikomori** [PayMaya/PayMaya-Android-SDK-v2#4]
Hi. I would like to ask why you guys dropped Android Lollipop support for this? I know that there have crashes when using WebView, and can be resolved by adding some on XML (based on my experience with version 1)

**Comment by rjarce** [comment]
Hi @jcchikikomori , this was just the original scope of the SDK. We can assess need to support lower Android versions. Do you have an urgent need to support lower Android versions?

**Comment by jcchikikomori** [comment]
> Hi @jcchikikomori , this was just the original scope of the SDK. We can assess need to support lower Android versions. Do you have an urgent need to support lower Android versions?

No urgency need for now (i think) as I have told my manager about this and currently waiting for my client's assessment since I have 1-9 percent of the audiences still using Android Lollipop

**Comment by jcchikikomori** [comment]
By the way, here's my manifest file on my forked SDK v1 for Android Lollipop support

The `uiMode` part fixes my issues on Android Lollipop

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.paymaya.sdk.android">

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />

    <application>
        <activity
            android:name=".checkout.PayMayaCheckoutActivity"
            android:configChanges="orientation|screenSize|uiMode"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
    </application>
</manifest>
```
